#!/bin/bash

VENV_PATH=".venv"

if [ ! -d "$VENV_PATH" ]; then
  echo "Environnement virtuel '$VENV_PATH' non trouvé. Création en cours..."
  python3 -m venv $VENV_PATH
fi

# Activation de l'environnement virtuel
source "$VENV_PATH/bin/activate"

# Installation des requirements
if [ -f "requirements.txt" ]; then
  echo "Installation des dépendances depuis requirements.txt..."
  pip install --upgrade pip
  pip install -r requirements.txt
else
  echo "Fichier requirements.txt introuvable !"
  exit 1
fi

echo "Installation terminée."
